# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1930, 1090)
        MainWindow.setMinimumSize(QtCore.QSize(640, 480))
        MainWindow.setMaximumSize(QtCore.QSize(2050, 1090))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_CamreaShow = QtWidgets.QLabel(self.groupBox)
        self.label_CamreaShow.setMinimumSize(QtCore.QSize(640, 480))
        self.label_CamreaShow.setMaximumSize(QtCore.QSize(1920, 1080))
        self.label_CamreaShow.setText("")
        self.label_CamreaShow.setObjectName("label_CamreaShow")
        self.horizontalLayout_9.addWidget(self.label_CamreaShow)
        self.horizontalLayout_12.addWidget(self.groupBox)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.horizontalSlider_5 = QtWidgets.QSlider(self.groupBox_4)
        self.horizontalSlider_5.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_5.setObjectName("horizontalSlider_5")
        self.horizontalLayout_2.addWidget(self.horizontalSlider_5)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.verticalLayout_3.addWidget(self.groupBox_4)
        self.horizontalLayout_12.addLayout(self.verticalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionDds = QtWidgets.QAction(MainWindow)
        self.actionDds.setObjectName("actionDds")
        self.action_TypeImage = QtWidgets.QAction(MainWindow)
        self.action_TypeImage.setObjectName("action_TypeImage")
        self.action_TypeVideo = QtWidgets.QAction(MainWindow)
        self.action_TypeVideo.setObjectName("action_TypeVideo")
        self.action_TypeCamrea = QtWidgets.QAction(MainWindow)
        self.action_TypeCamrea.setObjectName("action_TypeCamrea")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "主页面"))
        self.groupBox.setTitle(_translate("MainWindow", "实时视频"))
        self.groupBox_4.setTitle(_translate("MainWindow", "视频配置"))
        self.label_7.setText(_translate("MainWindow", "视频压缩率"))
        self.label_6.setText(_translate("MainWindow", "树莓派地址"))
        self.actionDds.setText(_translate("MainWindow", "你好"))
        self.action_TypeImage.setText(_translate("MainWindow", "图片"))
        self.action_TypeImage.setIconText(_translate("MainWindow", "√图片"))
        self.action_TypeVideo.setText(_translate("MainWindow", "视频"))
        self.action_TypeCamrea.setText(_translate("MainWindow", "摄像头"))
