# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SSHClient.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SSHClientWidget(object):
    def setupUi(self, SSHClientWidget):
        SSHClientWidget.setObjectName("SSHClientWidget")
        SSHClientWidget.resize(1086, 609)
        self.centralwidget = QtWidgets.QWidget(SSHClientWidget)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.horizontalLayout.addWidget(self.plainTextEdit)
        SSHClientWidget.setCentralWidget(self.centralwidget)

        self.retranslateUi(SSHClientWidget)
        QtCore.QMetaObject.connectSlotsByName(SSHClientWidget)

    def retranslateUi(self, SSHClientWidget):
        _translate = QtCore.QCoreApplication.translate
        SSHClientWidget.setWindowTitle(_translate("SSHClientWidget", "MainWindow"))
