# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'StartUpItem.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StartUpItem(object):
    def setupUi(self, StartUpItem):
        StartUpItem.setObjectName("StartUpItem")
        StartUpItem.resize(802, 600)
        self.centralwidget = QtWidgets.QWidget(StartUpItem)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget_StartupItem = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_StartupItem.setObjectName("tableWidget_StartupItem")
        self.tableWidget_StartupItem.setColumnCount(4)
        self.tableWidget_StartupItem.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_StartupItem.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_StartupItem.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_StartupItem.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_StartupItem.setHorizontalHeaderItem(3, item)
        self.verticalLayout.addWidget(self.tableWidget_StartupItem)
        StartUpItem.setCentralWidget(self.centralwidget)

        self.retranslateUi(StartUpItem)
        QtCore.QMetaObject.connectSlotsByName(StartUpItem)

    def retranslateUi(self, StartUpItem):
        _translate = QtCore.QCoreApplication.translate
        StartUpItem.setWindowTitle(_translate("StartUpItem", "开机启动项"))
        item = self.tableWidget_StartupItem.horizontalHeaderItem(0)
        item.setText(_translate("StartUpItem", "启动命令行"))
        item = self.tableWidget_StartupItem.horizontalHeaderItem(1)
        item.setText(_translate("StartUpItem", "启动延时"))
        item = self.tableWidget_StartupItem.horizontalHeaderItem(2)
        item.setText(_translate("StartUpItem", "启动状态"))
        item = self.tableWidget_StartupItem.horizontalHeaderItem(3)
        item.setText(_translate("StartUpItem", "备注"))
